package at.swimmesberger.bo2.profile.entity;

public enum ProfileDataValueType {
    GOLDEN_KEYS, BADASS_RANK, BADASS_TOKENS, MAXIMUM_HEALTH, SHIELD_CAPACITY, SHIELD_RECHARGE_DELAY, SHIELD_RECHARGE_RATE, MELEE_DAMAGE,
    GRENADE_DAMAGE, GUN_ACCURACY, GUN_DAMAGE, FIRE_RATE, RECOIL_REDUCTION, RELOAD_SPEED, ELEMENTAL_EFFECT_CHANCE, ELEMENTAL_EFFECT_DAMAGE, CRITICAL_HIT_DAMAGE,
    UNLOCK_ALL_CUSTOMIZATIONS, LOCK_ALL_CUSTOMIZATIONS
}
